"""Stable boundaries for post-V1 integrations.

V1 deliberately does not open the Kinect, Stewart serial port, or roller-ball
HID. V2/V3 adapters implement these protocols without changing the game engine
or cabinet UI state model.
"""

from __future__ import annotations

from typing import Protocol


class BallTrackingAdapter(Protocol):
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def current_cell(self) -> str | None: ...
    def tracking_confidence(self) -> float: ...


class TiltControlAdapter(Protocol):
    def initialize(self) -> None: ...
    def enable_play(self) -> None: ...
    def level(self) -> None: ...
    def shutdown(self) -> None: ...

